### ISSUE TITLE
dunfell-23.0.11 breaks backport of meta-qt5 (qt 5.12.4)

### ISSUE THREAD

**Issue by h5b** [jhnc-oss/yocto-manifests#16]
Our backport of meta-qt5 (qt 5.12.4) breaks with the advent of dunfell-23.0.11 and needs to be adapted

- [x] add layer meta-python2 to provide legacy-support for Python2
- [x] update [backport](https://github.com/jhnc-oss/meta-qt5/tree/backport/5.12.4-dunfell-23.0.11) to cope with changes in poky regarding BLUEZ, sip and Python
- [x] update repo config of "meta-qt5" accordingly (refer to backport)
- [x] check current layer

**Comment by h5b** [comment]
https://github.com/jhnc-oss/meta-qt5/commit/d70e8e937fb984312f28a36bcef0e6d96feba352

**Comment by h5b** [comment]
Fixed for 23.0.13 with https://github.com/jhnc-oss/meta-qt5/commit/19488722b5772d6db3680d7ba393cf9022f53d39
